// Generated by `npm run icons:names`. Runtime loads PNGs via require.context; this file is type-only.
export type IconName =
  | 'check'
  | 'checkmark'
  | 'chevron-left'
  | 'chevron-right'
  | 'close';
